name: simple
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - icc_rt=2022.1.0
  - intel-openmp=2023.1.0
  - libffi=3.4.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openssl=3.0.11
  - pip=23.2.1
  - python=3.11.5
  - scipy=1.11.1
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
